**Mounting The Google-Drive**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


**Importing pandas to read a dataset, matplotlib,seaborn import for plotting and libraries**

In [ ]:
import pandas as pd
import graphviz
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import plot_roc_curve
from sklearn.svm import SVC
import matplotlib.pyplot as plt

from sklearn.externals.six import StringIO  
from IPython.display import Image  
from sklearn.tree import export_graphviz
import pydotplus
from sklearn.neighbors import KNeighborsClassifier

**To read the WineQuality-Dataset**

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/winequality-red.csv')
print(data)

      fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.6

**To Generate descriptive Statistics Information through describe() method**

In [ ]:
data.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

**To Findout the top-rows of data of WineQuality-Dataset**

In [ ]:
data.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

**To find any null values in the data**

In [ ]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
data.shape

(1599, 12)

In [ ]:
data.groupby('quality').size()

quality
3     10
4     53
5    681
6    638
7    199
8     18
dtype: int64

**To convert the numerical values into array in a DataFrame:**

In [ ]:
a=data.values
print(a)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


**To dispaly the first 3 rows of X:**

In [ ]:
X=a[:,0:-1]
Y=a[:,11]

**Splitting the dataset into 70:30**

In [ ]:
X = data.drop('quality', axis=1)
Y= data['quality']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20, stratify=Y, random_state=42)
y_test.value_counts()

5    136
6    128
7     40
4     11
8      3
3      2
Name: quality, dtype: int64

In [ ]:
X.shape

(1599, 11)

**Decision-Tree Algorithm:**
It is a graphical representation for getting all the possible solutions to a problem/decision based on given conditions.. It is a tree-structured classifier, where internal nodes represent the features of a dataset, branches represent the decision rules and each leaf node represents the outcome.

**To Train Decision-Tree Model**

In [ ]:
tree = DecisionTreeClassifier(criterion='gini',min_samples_leaf=5,min_samples_split=5,max_depth=None,random_state=42)
clf=tree.fit(X_train, y_train)
pred = clf.predict(X_test)

 **To see the accuracy and classification-report of the DT model through Classification-Performance Metrics.**

In [ ]:
accuracy = accuracy_score(y_test, pred)
print(classification_report(y_test,pred))
print('DecisionTreeClassifier Accuracy Score: ',accuracy)

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.25      0.18      0.21        11
           5       0.65      0.65      0.65       136
           6       0.58      0.62      0.60       128
           7       0.54      0.50      0.52        40
           8       0.00      0.00      0.00         3

    accuracy                           0.59       320
   macro avg       0.34      0.33      0.33       320
weighted avg       0.58      0.59      0.59       320

DecisionTreeClassifier Accuracy Score:  0.59375


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**The scikit-learn machine library provides an implementation of the correlation statistic in the ch2 function. This function can be used in a feature selection strategy, such as selecting the top k most relevant features (largest values) via the SelectKBest class.**

In [ ]:
testing=SelectKBest(chi2,k='all')
score=testing.fit(X,Y)
set_printoptions(precision=4)
print(score.scores_)

[1.1261e+01 1.5580e+01 1.3026e+01 4.1233e+00 7.5243e-01 1.6194e+02
 2.7556e+03 2.3043e-04 1.5465e-01 4.5585e+00 4.6430e+01]


In [ ]:
X=a[:,0:-1]
Y=a[:,11]

To features the goal of recursive feature elimination (RFE) is to select features by recursively considering smaller and smaller sets of features. First, the estimator is trained on the initial set of features and the importance of each feature is obtained either through any specific attribute or callable. Then, the least important features are pruned from current set of features. That procedure is recursively repeated on the pruned set until the desired number of features to select is eventually reached.

**Selecting best features for Decision-tree classifier:**

In [ ]:
model= DecisionTreeClassifier()
rfe = RFE(model, 5)
fit = rfe.fit(X, Y)
print("Num Features: ", fit.n_features_)
print("Selected Features: ",fit.support_)
print("Feature Ranking: ",fit.ranking_)

rfe = RFE(model, 4)
fit = rfe.fit(X, Y)
print("Num Features: ", fit.n_features_)
print("Selected Features: ",fit.support_)
print("Feature Ranking: ",fit.ranking_)

rfe = RFE(model, 3)
fit = rfe.fit(X, Y)
print("Num Features: ", fit.n_features_)
print("Selected Features: ",fit.support_)
print("Feature Ranking: ",fit.ranking_)

Num Features:  5
Selected Features:  [False  True False  True False False  True False False  True  True]
Feature Ranking:  [6 1 3 1 2 5 1 7 4 1 1]
Num Features:  4
Selected Features:  [False  True False False False False  True False False  True  True]
Feature Ranking:  [8 1 5 2 4 7 1 3 6 1 1]
Num Features:  3
Selected Features:  [False False False False False False  True False False  True  True]
Feature Ranking:  [7 2 9 4 6 8 1 3 5 1 1]


In [ ]:
X=a[:,[3,4,6,9,10]]
X_train,X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)
lm= DecisionTreeClassifier() 
tree_model=lm.fit(X_train,Y_train)
y_pred=tree_model.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[ 0  0  1  0  0  0]
 [ 0  0  5  4  1  0]
 [ 1  3 93 29  4  0]
 [ 1  1 33 75 21  1]
 [ 0  1  5 17 18  1]
 [ 0  0  0  2  3  0]]
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         1
         4.0       0.00      0.00      0.00        10
         5.0       0.68      0.72      0.70       130
         6.0       0.59      0.57      0.58       132
         7.0       0.38      0.43      0.40        42
         8.0       0.00      0.00      0.00         5

    accuracy                           0.58       320
   macro avg       0.28      0.29      0.28       320
weighted avg       0.57      0.58      0.57       320



**Here,training the model for Decision-Tree classifier:**

In [ ]:
X=a[:,[3,4,9,10]]
X_train,X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)
lm1= DecisionTreeClassifier() 
tree_model1=lm1.fit(X_train,Y_train)
y_pred=tree_model1.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[ 0  0  0  1  0  0]
 [ 0  0  5  4  1  0]
 [ 2  5 92 26  4  1]
 [ 0  5 32 81 13  1]
 [ 0  0  7 15 19  1]
 [ 0  0  0  2  3  0]]
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         1
         4.0       0.00      0.00      0.00        10
         5.0       0.68      0.71      0.69       130
         6.0       0.63      0.61      0.62       132
         7.0       0.47      0.45      0.46        42
         8.0       0.00      0.00      0.00         5

    accuracy                           0.60       320
   macro avg       0.30      0.30      0.30       320
weighted avg       0.60      0.60      0.60       320



In [ ]:
X=a[:,[3,4,9]]
X_train,X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)
lm2= DecisionTreeClassifier() 
tree_model2=lm2.fit(X_train,Y_train)
y_pred=tree_model2.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[ 0  0  1  0  0  0]
 [ 0  0  4  5  1  0]
 [ 0  1 88 32  9  0]
 [ 0  3 45 67 16  1]
 [ 1  0  6 15 20  0]
 [ 0  0  1  1  3  0]]
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         1
         4.0       0.00      0.00      0.00        10
         5.0       0.61      0.68      0.64       130
         6.0       0.56      0.51      0.53       132
         7.0       0.41      0.48      0.44        42
         8.0       0.00      0.00      0.00         5

    accuracy                           0.55       320
   macro avg       0.26      0.28      0.27       320
weighted avg       0.53      0.55      0.54       320



**SVM Algorithm:**
SVM algorithm picks the one that has the maximum distance from the closest data points. Kernel SVM contains a non-linear transformation function to convert the complicated non-linearly separable data into linearly separable data.It performs the same in such a way that datasets belonging to different classes are allocated to different dimensions. 

In [ ]:
X=a[:,0:-1]
Y=a[:,11]
X_train,X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=7)

**To Train Support Vector Machine Tree Model**

In [ ]:
from sklearn.svm import SVC
svm_model = SVC(gamma='auto')
svm_model.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

 **To predict the Support Vector Machine model**

In [ ]:
predictions = svm_model.predict(X_test)

**To see the accuracy and classification-report of the SVM model through Classification-Performance Metrics.**

In [ ]:
from sklearn import metrics
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print('SVMClassifier Accuracy-Score: ',metrics.accuracy_score(y_test,predictions))

[[ 0  0  2  0  0  0]
 [ 0  0  5  6  0  0]
 [ 0  0 81 55  0  0]
 [ 0  0 76 51  1  0]
 [ 0  0 22 18  0  0]
 [ 0  0  2  1  0  0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.43      0.60      0.50       136
           6       0.39      0.40      0.39       128
           7       0.00      0.00      0.00        40
           8       0.00      0.00      0.00         3

    accuracy                           0.41       320
   macro avg       0.14      0.17      0.15       320
weighted avg       0.34      0.41      0.37       320

SVMClassifier Accuracy-Score:  0.4125


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
X=a[:,0:-1]
Y=a[:,11]

**Selecting best features for SupportVectorMachine Model:**

In [ ]:
model2 = SVC(kernel='linear') 
rfe = RFE(model2, 4)
fit = rfe.fit(X, Y)
print("Num Features: ", fit.n_features_)
print("Selected Features: ",fit.support_)
print("Feature Ranking: ",fit.ranking_)

Num Features:  4
Selected Features:  [False  True False False False False False False  True  True  True]
Feature Ranking:  [5 1 3 4 2 6 8 7 1 1 1]


**Here,training the model for SupportVectorMachine Model:**

In [ ]:
X=a[:,[3,4,9,10]]
X_train,X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)
svm=SVC(kernel='linear') 
svmmodel=svm.fit(X_train,Y_train)
y_pred=svmmodel.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[  0   0   1   0   0   0]
 [  0   0   6   4   0   0]
 [  0   0 107  23   0   0]
 [  0   0  58  74   0   0]
 [  0   0   4  38   0   0]
 [  0   0   0   5   0   0]]
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         1
         4.0       0.00      0.00      0.00        10
         5.0       0.61      0.82      0.70       130
         6.0       0.51      0.56      0.54       132
         7.0       0.00      0.00      0.00        42
         8.0       0.00      0.00      0.00         5

    accuracy                           0.57       320
   macro avg       0.19      0.23      0.21       320
weighted avg       0.46      0.57      0.51       320



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
X=a[:,[0,5,6,7]]
X_train,X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=42)
svm1=SVC(kernel='linear') 
svmmodel1=svm1.fit(X_train,Y_train)
y_pred=svmmodel1.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[  0   0   0   1   0   0]
 [  0   0   1   9   0   0]
 [  0   0  46  84   0   0]
 [  0   0  21 111   0   0]
 [  0   0   3  39   0   0]
 [  0   0   1   4   0   0]]
              precision    recall  f1-score   support

         3.0       0.00      0.00      0.00         1
         4.0       0.00      0.00      0.00        10
         5.0       0.64      0.35      0.46       130
         6.0       0.45      0.84      0.58       132
         7.0       0.00      0.00      0.00        42
         8.0       0.00      0.00      0.00         5

    accuracy                           0.49       320
   macro avg       0.18      0.20      0.17       320
weighted avg       0.44      0.49      0.43       320



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**KNN Algorithm:**
It is a lazy learning algorithm since it doesn't have a specialized training phase. Rather, it uses all of the data for training while classifying a new data point or instance.

**To Train K-Nearest Neighbors Model**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

 **To predict the K-Nearest Neighbors model**

In [ ]:
pre = knn_model.predict(X_test)

**To see the accuracy and classification-report of the K-Nearest Neighbors model through Classification-Performance Metrics.**

In [ ]:
from sklearn import metrics
print(confusion_matrix(y_test,pre))
print(classification_report(y_test,pre))
print('KNNClassifier Accuracy-Score: ',metrics.accuracy_score(y_test,pre))

[[ 0  0  1  1  0  0]
 [ 0  0  8  3  0  0]
 [ 0  1 86 45  4  0]
 [ 0  0 55 64  9  0]
 [ 0  0 15 20  5  0]
 [ 0  0  0  1  2  0]]
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        11
           5       0.52      0.63      0.57       136
           6       0.48      0.50      0.49       128
           7       0.25      0.12      0.17        40
           8       0.00      0.00      0.00         3

    accuracy                           0.48       320
   macro avg       0.21      0.21      0.20       320
weighted avg       0.44      0.48      0.46       320

KNNClassifier Accuracy-Score:  0.484375


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
X=data.drop(['quality'],axis=1)
Y=data['quality'].values

In [ ]:
testing=SelectKBest(chi2,k='all')
score=testing.fit(X, Y)
set_printoptions(precision=4)
print(score.scores_)

[1.1261e+01 1.5580e+01 1.3026e+01 4.1233e+00 7.5243e-01 1.6194e+02
 2.7556e+03 2.3043e-04 1.5465e-01 4.5585e+00 4.6430e+01]


In [ ]:
X=a[:,0:-1]
Y=a[:,11]

**Selecting best features and training the model for KNN classifier:**

In [ ]:
model3 = KNeighborsClassifier()
rfe = RFE(model3, 4)
fit = rfe.fit(X,Y)
print("Num Features: ", fit.n_features_)
print("Selected Features: ",fit.support_)
print("Feature Ranking: ",fit.ranking_)

Num Features:  4
Selected Features:  [ True  True  True  True]
Feature Ranking:  [1 1 1 1]


In [ ]:
X=a[:,[3,4,9,10]]
X_train,X_test, Y_train, Y_test=train_test_split(X,Y, test_size=0.2,random_state=7)
knn=KNeighborsClassifier(n_neighbors=7) 
knnmodel=knn.fit(X_train,Y_train)
y_pred=knnmodel.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[ 0  7  2  1  0]
 [ 0 86 33  4  0]
 [ 0 47 83 16  0]
 [ 0  6 14 17  0]
 [ 0  1  0  3  0]]
              precision    recall  f1-score   support

         4.0       0.00      0.00      0.00        10
         5.0       0.59      0.70      0.64       123
         6.0       0.63      0.57      0.60       146
         7.0       0.41      0.46      0.44        37
         8.0       0.00      0.00      0.00         4

    accuracy                           0.58       320
   macro avg       0.33      0.35      0.33       320
weighted avg       0.56      0.58      0.57       320



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
